// src/app/layout.tsx
import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google"; // Import Kumbh Sans from Google Fonts
import "./globals.css"; // Tailwind is imported here, so it's globally available
import { Toaster } from "react-hot-toast"; // Import Toaster from react-hot-toast

// Load Kumbh Sans Google Font
const kumbhSans = Kumbh_Sans({
  subsets: ["latin"],
  weight: ["400", "700"], // Customize the weights you need
  variable: "--font-kumbh-sans", // Tailwind CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kumbhSans.variable} antialiased`} // Use Kumbh Sans variable here
      >
        <Toaster position="top-right" reverseOrder={false} /> {/* Add Toaster here */}
        {children}
      </body>
    </html>
  );
}
